language: php

matrix:
  fast_finish: true

  allow_failures:
    - php: nightly

  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly

before_script:
  - phpenv config-rm xdebug.ini
  - composer validate --strict
  - composer install --no-interaction --no-progress --no-suggest
